services:
    server:
        build:
            context: .
            target: test
            no_cache: true
        environment:
            PGPASSWORD: secret-test-password
            PGHOST: db
            PGDATABASE: PritStreck
        env_file: ".env"
        restart: always
        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres
        restart: always
        user: postgres
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_DB=PritStreck
            - POSTGRES_PASSWORD=secret-test-password
        expose:
            - 5432
        healthcheck:
            test: ['CMD', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
          - '54320:5432'