services:
    server:
        environment:
            PGPASSWORD_FILE: null
            PGPASSWORD: secret-dev-password
    db:
        environment:
            POSTGRES_PASSWORD_FILE: null
            POSTGRES_PASSWORD: secret-dev-password
            DEV_MODE: true
        volumes:
            - dev-db-data:/var/lib/postgresql/data
        extends:
            file: docker-compose.yaml
            service: db
        ports:
          - '54320:5432'
volumes:
    dev-db-data: