DROP TABLE IF EXISTS PurchasedItems;
DROP TABLE IF EXISTS Deposits;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS Prices;
DROP TABLE IF EXISTS FavoriteItems;
DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Groups;